export default {
    text: '#fffae7',
    white: '#fff',
    black: '#000',
    yellow: '#ffd33d',
    mutedYellow: '#e6be36',
    errorText: '#fd0303',
    background: '#25292e',
    backgroundLight: '#fff',
    backgroundDelete: '#fd0303',
    backgroundAlternate: '#8d98a5',
    border: '#fff',
    borderEdit: '#ccc',
    borderError: '#fd0303',
};
